### ISSUE TITLE
Serve spatiotemporal data

### ISSUE THREAD

**Issue by jpolchlo** [geotrellis/geotrellis-server#3]
We cannot yet serve layers keyed by `SpaceTimeKey`.  This requires filling in the temporal ranges in DescribeCoverage (possibly GetCapabilities for the 1.1.1 layers), and delivering the correct keys in GetCoverage.

## Overall
- [x] [Add configuration option to mark GeoTrellis layer sources as spatiotemporal](https://github.com/geotrellis/geotrellis-server/issues/219)
- [x] Implement [`RasterCatalog`](https://github.com/geotrellis/geotrellis-server/issues/162)
- [x] Update [`{WCS|WMS|WMTS}Model`](https://github.com/geotrellis/geotrellis-server/issues/163) to respond to spatiotemporal queries 

## Version 1.1.1
- [x] [WCS Temporal layers](https://github.com/azavea/geotrellis/issues/232)
- [x] [WMS Temporal layers](https://github.com/azavea/geotrellis/issues/231)
- [x] `DescribeCoverage` response contains [`TemporalDomain`](https://github.com/geotrellis/geotrellis-server/issues/160)
