### ISSUE TITLE
Franklin Collections improvements

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-server#328]
- [x] Separately index time fields https://github.com/azavea/franklin/issues/629
- [x] Re-calculate collection extents on item additions / removals https://github.com/azavea/franklin/issues/615
- [x] Model interval ADT with periodic and non-periodic intervals https://github.com/azavea/stac4s/issues/268
